#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Nhom1_QLMB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChuyenBay")]
	public partial class DataSourceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuyenBay(ChuyenBay instance);
    partial void UpdateChuyenBay(ChuyenBay instance);
    partial void DeleteChuyenBay(ChuyenBay instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertDatCho(DatCho instance);
    partial void UpdateDatCho(DatCho instance);
    partial void DeleteDatCho(DatCho instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLichBay(LichBay instance);
    partial void UpdateLichBay(LichBay instance);
    partial void DeleteLichBay(LichBay instance);
    partial void InsertLoaiMayBay(LoaiMayBay instance);
    partial void UpdateLoaiMayBay(LoaiMayBay instance);
    partial void DeleteLoaiMayBay(LoaiMayBay instance);
    partial void InsertMayBay(MayBay instance);
    partial void UpdateMayBay(MayBay instance);
    partial void DeleteMayBay(MayBay instance);
    #endregion
		
		public DataSourceDataContext() : 
				base(global::BTL_Nhom1_QLMB.Properties.Settings.Default.QuanLyChuyenBayConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataSourceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuyenBay> ChuyenBays
		{
			get
			{
				return this.GetTable<ChuyenBay>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<DatCho> DatChos
		{
			get
			{
				return this.GetTable<DatCho>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LichBay> LichBays
		{
			get
			{
				return this.GetTable<LichBay>();
			}
		}
		
		public System.Data.Linq.Table<LoaiMayBay> LoaiMayBays
		{
			get
			{
				return this.GetTable<LoaiMayBay>();
			}
		}
		
		public System.Data.Linq.Table<MayBay> MayBays
		{
			get
			{
				return this.GetTable<MayBay>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuyenBay")]
	public partial class ChuyenBay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macb;
		
		private string _sbdi;
		
		private string _sbden;
		
		private System.Nullable<System.TimeSpan> _giodi;
		
		private System.Nullable<System.TimeSpan> _gioden;
		
		private System.Nullable<System.DateTime> _ngaydi;
		
		private System.Nullable<System.DateTime> _ngayden;
		
		private string _sohieu;
		
		private EntitySet<DatCho> _DatChos;
		
		private EntitySet<LichBay> _LichBays;
		
		private EntityRef<MayBay> _MayBay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacbChanging(string value);
    partial void OnmacbChanged();
    partial void OnsbdiChanging(string value);
    partial void OnsbdiChanged();
    partial void OnsbdenChanging(string value);
    partial void OnsbdenChanged();
    partial void OngiodiChanging(System.Nullable<System.TimeSpan> value);
    partial void OngiodiChanged();
    partial void OngiodenChanging(System.Nullable<System.TimeSpan> value);
    partial void OngiodenChanged();
    partial void OnngaydiChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydiChanged();
    partial void OnngaydenChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydenChanged();
    partial void OnsohieuChanging(string value);
    partial void OnsohieuChanged();
    #endregion
		
		public ChuyenBay()
		{
			this._DatChos = new EntitySet<DatCho>(new Action<DatCho>(this.attach_DatChos), new Action<DatCho>(this.detach_DatChos));
			this._LichBays = new EntitySet<LichBay>(new Action<LichBay>(this.attach_LichBays), new Action<LichBay>(this.detach_LichBays));
			this._MayBay = default(EntityRef<MayBay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macb", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macb
		{
			get
			{
				return this._macb;
			}
			set
			{
				if ((this._macb != value))
				{
					this.OnmacbChanging(value);
					this.SendPropertyChanging();
					this._macb = value;
					this.SendPropertyChanged("macb");
					this.OnmacbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbdi", DbType="NVarChar(50)")]
		public string sbdi
		{
			get
			{
				return this._sbdi;
			}
			set
			{
				if ((this._sbdi != value))
				{
					this.OnsbdiChanging(value);
					this.SendPropertyChanging();
					this._sbdi = value;
					this.SendPropertyChanged("sbdi");
					this.OnsbdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sbden", DbType="NVarChar(50)")]
		public string sbden
		{
			get
			{
				return this._sbden;
			}
			set
			{
				if ((this._sbden != value))
				{
					this.OnsbdenChanging(value);
					this.SendPropertyChanging();
					this._sbden = value;
					this.SendPropertyChanged("sbden");
					this.OnsbdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giodi", DbType="Time")]
		public System.Nullable<System.TimeSpan> giodi
		{
			get
			{
				return this._giodi;
			}
			set
			{
				if ((this._giodi != value))
				{
					this.OngiodiChanging(value);
					this.SendPropertyChanging();
					this._giodi = value;
					this.SendPropertyChanged("giodi");
					this.OngiodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioden", DbType="Time")]
		public System.Nullable<System.TimeSpan> gioden
		{
			get
			{
				return this._gioden;
			}
			set
			{
				if ((this._gioden != value))
				{
					this.OngiodenChanging(value);
					this.SendPropertyChanging();
					this._gioden = value;
					this.SendPropertyChanged("gioden");
					this.OngiodenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this.OnngaydiChanging(value);
					this.SendPropertyChanging();
					this._ngaydi = value;
					this.SendPropertyChanged("ngaydi");
					this.OnngaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayden", DbType="Date")]
		public System.Nullable<System.DateTime> ngayden
		{
			get
			{
				return this._ngayden;
			}
			set
			{
				if ((this._ngayden != value))
				{
					this.OnngaydenChanging(value);
					this.SendPropertyChanging();
					this._ngayden = value;
					this.SendPropertyChanged("ngayden");
					this.OnngaydenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohieu", DbType="NVarChar(10)")]
		public string sohieu
		{
			get
			{
				return this._sohieu;
			}
			set
			{
				if ((this._sohieu != value))
				{
					if (this._MayBay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsohieuChanging(value);
					this.SendPropertyChanging();
					this._sohieu = value;
					this.SendPropertyChanged("sohieu");
					this.OnsohieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenBay_DatCho", Storage="_DatChos", ThisKey="macb", OtherKey="macb")]
		public EntitySet<DatCho> DatChos
		{
			get
			{
				return this._DatChos;
			}
			set
			{
				this._DatChos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenBay_LichBay", Storage="_LichBays", ThisKey="macb", OtherKey="macb")]
		public EntitySet<LichBay> LichBays
		{
			get
			{
				return this._LichBays;
			}
			set
			{
				this._LichBays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MayBay_ChuyenBay", Storage="_MayBay", ThisKey="sohieu", OtherKey="sohieu", IsForeignKey=true)]
		public MayBay MayBay
		{
			get
			{
				return this._MayBay.Entity;
			}
			set
			{
				MayBay previousValue = this._MayBay.Entity;
				if (((previousValue != value) 
							|| (this._MayBay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MayBay.Entity = null;
						previousValue.ChuyenBays.Remove(this);
					}
					this._MayBay.Entity = value;
					if ((value != null))
					{
						value.ChuyenBays.Add(this);
						this._sohieu = value.sohieu;
					}
					else
					{
						this._sohieu = default(string);
					}
					this.SendPropertyChanged("MayBay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatChos(DatCho entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenBay = this;
		}
		
		private void detach_DatChos(DatCho entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenBay = null;
		}
		
		private void attach_LichBays(LichBay entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenBay = this;
		}
		
		private void detach_LichBays(LichBay entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenBay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ten_dn;
		
		private string _matkhau;
		
		private System.Nullable<int> _loainguoidung;
		
		private EntitySet<KhachHang> _KhachHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onten_dnChanging(string value);
    partial void Onten_dnChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnloainguoidungChanging(System.Nullable<int> value);
    partial void OnloainguoidungChanged();
    #endregion
		
		public NguoiDung()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dn", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ten_dn
		{
			get
			{
				return this._ten_dn;
			}
			set
			{
				if ((this._ten_dn != value))
				{
					this.Onten_dnChanging(value);
					this.SendPropertyChanging();
					this._ten_dn = value;
					this.SendPropertyChanged("ten_dn");
					this.Onten_dnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(20)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loainguoidung", DbType="Int")]
		public System.Nullable<int> loainguoidung
		{
			get
			{
				return this._loainguoidung;
			}
			set
			{
				if ((this._loainguoidung != value))
				{
					this.OnloainguoidungChanging(value);
					this.SendPropertyChanging();
					this._loainguoidung = value;
					this.SendPropertyChanged("loainguoidung");
					this.OnloainguoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_KhachHang", Storage="_KhachHangs", ThisKey="ten_dn", OtherKey="ten_dn")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatCho")]
	public partial class DatCho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _soghe;
		
		private string _makh;
		
		private string _macb;
		
		private System.Nullable<System.DateTime> _thoigiandi;
		
		private EntityRef<ChuyenBay> _ChuyenBay;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsogheChanging(string value);
    partial void OnsogheChanged();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OnmacbChanging(string value);
    partial void OnmacbChanged();
    partial void OnthoigiandiChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigiandiChanged();
    #endregion
		
		public DatCho()
		{
			this._ChuyenBay = default(EntityRef<ChuyenBay>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soghe", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string soghe
		{
			get
			{
				return this._soghe;
			}
			set
			{
				if ((this._soghe != value))
				{
					this.OnsogheChanging(value);
					this.SendPropertyChanging();
					this._soghe = value;
					this.SendPropertyChanged("soghe");
					this.OnsogheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="NVarChar(10)")]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macb", DbType="NVarChar(10)")]
		public string macb
		{
			get
			{
				return this._macb;
			}
			set
			{
				if ((this._macb != value))
				{
					if (this._ChuyenBay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacbChanging(value);
					this.SendPropertyChanging();
					this._macb = value;
					this.SendPropertyChanged("macb");
					this.OnmacbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigiandi", DbType="Date")]
		public System.Nullable<System.DateTime> thoigiandi
		{
			get
			{
				return this._thoigiandi;
			}
			set
			{
				if ((this._thoigiandi != value))
				{
					this.OnthoigiandiChanging(value);
					this.SendPropertyChanging();
					this._thoigiandi = value;
					this.SendPropertyChanged("thoigiandi");
					this.OnthoigiandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenBay_DatCho", Storage="_ChuyenBay", ThisKey="macb", OtherKey="macb", IsForeignKey=true, DeleteRule="SET NULL")]
		public ChuyenBay ChuyenBay
		{
			get
			{
				return this._ChuyenBay.Entity;
			}
			set
			{
				ChuyenBay previousValue = this._ChuyenBay.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenBay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenBay.Entity = null;
						previousValue.DatChos.Remove(this);
					}
					this._ChuyenBay.Entity = value;
					if ((value != null))
					{
						value.DatChos.Add(this);
						this._macb = value.macb;
					}
					else
					{
						this._macb = default(string);
					}
					this.SendPropertyChanged("ChuyenBay");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DatCho", Storage="_KhachHang", ThisKey="makh", OtherKey="makh", IsForeignKey=true, DeleteRule="SET NULL")]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DatChos.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DatChos.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _ten;
		
		private string _diachi;
		
		private string _sdt;
		
		private string _cmt;
		
		private string _ten_dn;
		
		private System.Nullable<int> _dadatcho;
		
		private EntitySet<DatCho> _DatChos;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OncmtChanging(string value);
    partial void OncmtChanged();
    partial void Onten_dnChanging(string value);
    partial void Onten_dnChanged();
    partial void OndadatchoChanging(System.Nullable<int> value);
    partial void OndadatchoChanged();
    #endregion
		
		public KhachHang()
		{
			this._DatChos = new EntitySet<DatCho>(new Action<DatCho>(this.attach_DatChos), new Action<DatCho>(this.detach_DatChos));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NVarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmt", DbType="NVarChar(50)")]
		public string cmt
		{
			get
			{
				return this._cmt;
			}
			set
			{
				if ((this._cmt != value))
				{
					this.OncmtChanging(value);
					this.SendPropertyChanging();
					this._cmt = value;
					this.SendPropertyChanged("cmt");
					this.OncmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dn", DbType="VarChar(20)")]
		public string ten_dn
		{
			get
			{
				return this._ten_dn;
			}
			set
			{
				if ((this._ten_dn != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onten_dnChanging(value);
					this.SendPropertyChanging();
					this._ten_dn = value;
					this.SendPropertyChanged("ten_dn");
					this.Onten_dnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dadatcho", DbType="Int")]
		public System.Nullable<int> dadatcho
		{
			get
			{
				return this._dadatcho;
			}
			set
			{
				if ((this._dadatcho != value))
				{
					this.OndadatchoChanging(value);
					this.SendPropertyChanging();
					this._dadatcho = value;
					this.SendPropertyChanged("dadatcho");
					this.OndadatchoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DatCho", Storage="_DatChos", ThisKey="makh", OtherKey="makh")]
		public EntitySet<DatCho> DatChos
		{
			get
			{
				return this._DatChos;
			}
			set
			{
				this._DatChos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_KhachHang", Storage="_NguoiDung", ThisKey="ten_dn", OtherKey="ten_dn", IsForeignKey=true, DeleteRule="SET NULL")]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._ten_dn = value.ten_dn;
					}
					else
					{
						this._ten_dn = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatChos(DatCho entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DatChos(DatCho entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichBay")]
	public partial class LichBay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _ngaydi;
		
		private string _macb;
		
		private string _sohieu;
		
		private EntityRef<ChuyenBay> _ChuyenBay;
		
		private EntityRef<MayBay> _MayBay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnngaydiChanging(System.DateTime value);
    partial void OnngaydiChanged();
    partial void OnmacbChanging(string value);
    partial void OnmacbChanged();
    partial void OnsohieuChanging(string value);
    partial void OnsohieuChanged();
    #endregion
		
		public LichBay()
		{
			this._ChuyenBay = default(EntityRef<ChuyenBay>);
			this._MayBay = default(EntityRef<MayBay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this.OnngaydiChanging(value);
					this.SendPropertyChanging();
					this._ngaydi = value;
					this.SendPropertyChanged("ngaydi");
					this.OnngaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macb", DbType="NVarChar(10)")]
		public string macb
		{
			get
			{
				return this._macb;
			}
			set
			{
				if ((this._macb != value))
				{
					if (this._ChuyenBay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacbChanging(value);
					this.SendPropertyChanging();
					this._macb = value;
					this.SendPropertyChanged("macb");
					this.OnmacbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohieu", DbType="NVarChar(10)")]
		public string sohieu
		{
			get
			{
				return this._sohieu;
			}
			set
			{
				if ((this._sohieu != value))
				{
					if (this._MayBay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsohieuChanging(value);
					this.SendPropertyChanging();
					this._sohieu = value;
					this.SendPropertyChanged("sohieu");
					this.OnsohieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenBay_LichBay", Storage="_ChuyenBay", ThisKey="macb", OtherKey="macb", IsForeignKey=true, DeleteRule="SET NULL")]
		public ChuyenBay ChuyenBay
		{
			get
			{
				return this._ChuyenBay.Entity;
			}
			set
			{
				ChuyenBay previousValue = this._ChuyenBay.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenBay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenBay.Entity = null;
						previousValue.LichBays.Remove(this);
					}
					this._ChuyenBay.Entity = value;
					if ((value != null))
					{
						value.LichBays.Add(this);
						this._macb = value.macb;
					}
					else
					{
						this._macb = default(string);
					}
					this.SendPropertyChanged("ChuyenBay");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MayBay_LichBay", Storage="_MayBay", ThisKey="sohieu", OtherKey="sohieu", IsForeignKey=true, DeleteRule="SET NULL")]
		public MayBay MayBay
		{
			get
			{
				return this._MayBay.Entity;
			}
			set
			{
				MayBay previousValue = this._MayBay.Entity;
				if (((previousValue != value) 
							|| (this._MayBay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MayBay.Entity = null;
						previousValue.LichBays.Remove(this);
					}
					this._MayBay.Entity = value;
					if ((value != null))
					{
						value.LichBays.Add(this);
						this._sohieu = value.sohieu;
					}
					else
					{
						this._sohieu = default(string);
					}
					this.SendPropertyChanged("MayBay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiMayBay")]
	public partial class LoaiMayBay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloai;
		
		private string _hang_sx;
		
		private EntitySet<MayBay> _MayBays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void Onhang_sxChanging(string value);
    partial void Onhang_sxChanged();
    #endregion
		
		public LoaiMayBay()
		{
			this._MayBays = new EntitySet<MayBay>(new Action<MayBay>(this.attach_MayBays), new Action<MayBay>(this.detach_MayBays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hang_sx", DbType="NVarChar(50)")]
		public string hang_sx
		{
			get
			{
				return this._hang_sx;
			}
			set
			{
				if ((this._hang_sx != value))
				{
					this.Onhang_sxChanging(value);
					this.SendPropertyChanging();
					this._hang_sx = value;
					this.SendPropertyChanged("hang_sx");
					this.Onhang_sxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiMayBay_MayBay", Storage="_MayBays", ThisKey="maloai", OtherKey="maloai")]
		public EntitySet<MayBay> MayBays
		{
			get
			{
				return this._MayBays;
			}
			set
			{
				this._MayBays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MayBays(MayBay entity)
		{
			this.SendPropertyChanging();
			entity.LoaiMayBay = this;
		}
		
		private void detach_MayBays(MayBay entity)
		{
			this.SendPropertyChanging();
			entity.LoaiMayBay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MayBay")]
	public partial class MayBay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sohieu;
		
		private string _maloai;
		
		private EntitySet<ChuyenBay> _ChuyenBays;
		
		private EntitySet<LichBay> _LichBays;
		
		private EntityRef<LoaiMayBay> _LoaiMayBay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsohieuChanging(string value);
    partial void OnsohieuChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    #endregion
		
		public MayBay()
		{
			this._ChuyenBays = new EntitySet<ChuyenBay>(new Action<ChuyenBay>(this.attach_ChuyenBays), new Action<ChuyenBay>(this.detach_ChuyenBays));
			this._LichBays = new EntitySet<LichBay>(new Action<LichBay>(this.attach_LichBays), new Action<LichBay>(this.detach_LichBays));
			this._LoaiMayBay = default(EntityRef<LoaiMayBay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sohieu", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sohieu
		{
			get
			{
				return this._sohieu;
			}
			set
			{
				if ((this._sohieu != value))
				{
					this.OnsohieuChanging(value);
					this.SendPropertyChanging();
					this._sohieu = value;
					this.SendPropertyChanged("sohieu");
					this.OnsohieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(10)")]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._LoaiMayBay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MayBay_ChuyenBay", Storage="_ChuyenBays", ThisKey="sohieu", OtherKey="sohieu")]
		public EntitySet<ChuyenBay> ChuyenBays
		{
			get
			{
				return this._ChuyenBays;
			}
			set
			{
				this._ChuyenBays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MayBay_LichBay", Storage="_LichBays", ThisKey="sohieu", OtherKey="sohieu")]
		public EntitySet<LichBay> LichBays
		{
			get
			{
				return this._LichBays;
			}
			set
			{
				this._LichBays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiMayBay_MayBay", Storage="_LoaiMayBay", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true, DeleteRule="SET NULL")]
		public LoaiMayBay LoaiMayBay
		{
			get
			{
				return this._LoaiMayBay.Entity;
			}
			set
			{
				LoaiMayBay previousValue = this._LoaiMayBay.Entity;
				if (((previousValue != value) 
							|| (this._LoaiMayBay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiMayBay.Entity = null;
						previousValue.MayBays.Remove(this);
					}
					this._LoaiMayBay.Entity = value;
					if ((value != null))
					{
						value.MayBays.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(string);
					}
					this.SendPropertyChanged("LoaiMayBay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuyenBays(ChuyenBay entity)
		{
			this.SendPropertyChanging();
			entity.MayBay = this;
		}
		
		private void detach_ChuyenBays(ChuyenBay entity)
		{
			this.SendPropertyChanging();
			entity.MayBay = null;
		}
		
		private void attach_LichBays(LichBay entity)
		{
			this.SendPropertyChanging();
			entity.MayBay = this;
		}
		
		private void detach_LichBays(LichBay entity)
		{
			this.SendPropertyChanging();
			entity.MayBay = null;
		}
	}
}
#pragma warning restore 1591
